// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJa7zErHa42a1zmozkmg6sDSJF64aovF8',
    appId: '1:711034811104:web:72e8fd9b8fe92f2036d685',
    messagingSenderId: '711034811104',
    projectId: 'final-exam-11c5d',
    authDomain: 'final-exam-11c5d.firebaseapp.com',
    storageBucket: 'final-exam-11c5d.appspot.com',
    measurementId: 'G-BE0PXVM18Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByfY4BpJLJ8l9nK9s-QhOyTznsUaL-c8o',
    appId: '1:711034811104:android:bab26752c7829a9836d685',
    messagingSenderId: '711034811104',
    projectId: 'final-exam-11c5d',
    storageBucket: 'final-exam-11c5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbLlKWvAoWLqb9V7vc_vInnp6T62wwrSU',
    appId: '1:711034811104:ios:8b0af160f6f376e836d685',
    messagingSenderId: '711034811104',
    projectId: 'final-exam-11c5d',
    storageBucket: 'final-exam-11c5d.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbLlKWvAoWLqb9V7vc_vInnp6T62wwrSU',
    appId: '1:711034811104:ios:8b0af160f6f376e836d685',
    messagingSenderId: '711034811104',
    projectId: 'final-exam-11c5d',
    storageBucket: 'final-exam-11c5d.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJa7zErHa42a1zmozkmg6sDSJF64aovF8',
    appId: '1:711034811104:web:859e97b6884bdf8a36d685',
    messagingSenderId: '711034811104',
    projectId: 'final-exam-11c5d',
    authDomain: 'final-exam-11c5d.firebaseapp.com',
    storageBucket: 'final-exam-11c5d.appspot.com',
    measurementId: 'G-SWHEGFYPXT',
  );
}
